#currently, i just support the file,fastdfs,seaweedfs  as the storage target 
#if any one want the image server to adapt other storage target 
#please pull request
#当前，只支持"文件"，"seaweedfs"作为存储目标
#如果需要支持其他的存储目标，请联系我




#if choose local file system as storage target then uncomment this section
#and  comment the  "seaweedfs" section 
#caution：this will limit the storage size to a few TB which is the maxmal size of one server.  but it is suffient to most of website
#如果只想使用本地文件作为存储目标，解开这个部分的注释，同时给"seaweedfs"加上注释
#注意，这种配置下，只能使用单台服务器的存储能力，一般是TB以内，但对于绝大多数网站而言，这已经足够
storageType = "file"
#be careful the last char should not be "/" or it will occure error on linux
#注意最后一个字符不能是/，否则在linux上会报错
fileDir = "/var/fqimg/data"



#如果想使用seaweedfs作为存储目标，解开这个部分的注释，同时给"file"加上注释
#if choose seaweedfs as storage target then uncomment this section
#and  comment the  "file" section 

#storageType="seaweedfs"
#weedMasterUrl="http://192.168.76.180:9333"



httpPort=80

#if this value set https will be open
httpsPort=443
httpsPublicKeyPath="/root/.acme.sh/fqimg.com/fqimg.com.cer"
httpsPrivateKeyPath="/root/.acme.sh/fqimg.com/fqimg.com.key"


#custom favorite icon
#自定义网站的 favorite icon
#faviconPath="./favicon.ico"



#if this section is set 
#the request url will append the following string to the url  
#at the circumstance of no command appearing 
#当请求连接不带任何命令的时候，下面的命令会给被默认加上
#defaultAction="c=fit&w=800&h=800|c=jpeg&q=70"


#local file cache put here, this should be set always set 
# it can improve performace by great magnitude   maybe  50 times faster
#图片服务器缓存配置。
#图片的动态操作非常慢，缓存是把操作之后的结果缓存在某个目录
#这个非常重要，设置这个，可以是使性能得到几十倍的提高
fileCacheDir= "/var/fqimg/cache/"
fileCacheSize=10000
getForceAction="mark=a"


#access control put here , but  uploadDeny   and  uploadAllowed can only set one
#can be  ip address or  CIDR  format network
#上传控制，允许或禁止只能设置一个，不能同时设置。
#设置的值可以是单独的IP地址，或者是CIDR网段
#uploadIpAllowed=["192.168.1.1/16"]
#uploadIpDeny=["127.0.0.1","192.168.76.200"]
#uploadIpLookups=["RemoteAddr", "X-Forwarded-For", "X-Real-IP"]
corsAllow=true
imageUrlPrefix="http://fqimg.com/"
uploadKey="file"
#每个文件的大小限制，kb为单位
uploadFileSizeLimit=10240
#每次上传的文件数量限制，最大值为该值
uploadFileNmuLimit=1
#custom http headers  put here
#自定义http请求头部
[headers]
Cache-Control="max-age=9999999"
Server="fqimg"


#水印文件存放这里
#water markers  put here
[markers]
a="./mark.png"
# b="./markers/b.jpg"
# c="./markers/c.jpg"